# yaml-language-server: disable
# bitsightpy documentation generation yml
site_name: Bitsightpy Documentation
nav:
  - Home: index.md
  - Getting Started: quickstart.md
  - Users APIs: users.md
  - Portfolio APIs: portfolio.md
  - Insight APIs: insight.md
  - Folder APIs: folder.md
  - Companies APIs: companies.md
  - Findings APIs: findings.md
  - Alerts APIs: alerts.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
  

theme: 
  name: material
  palette:

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  features:
    - navigation.instant
    - navigation.instant.prefetch
  highlightjs: true
  user_color_mode_toggle: true
repo_url: https://github.com/0x41424142/bitsightpy
repo_name: Github
edit_uri: blob/main/docs/
site_author: Jake Lindsay <jake@jakelindsay.uk>
site_description: Documentation for the bitsightpy Python SDK. Make working with BitSight APIs easier.