"""
call_schema.py - Contains expected params/form data/headers/etc. for
each Bitsight API endpoint.
"""

from frozendict import frozendict

"""
Other than get_endpoints, dict is structred as follows:

dict[module][function] = {...}
"""

CALL_SCHEMA = frozendict(
    {
        "get_endpoints": {
            "endpoint": "",
            "params": [],
            "post_data": {},
            "use_requests_json_for_post": False,
            "method": ["GET"],
            "pagination": False,
        },
        "users": {
            "get_users": {
                "endpoint": "ratings/v2/users",
                "params": [
                    "limit",
                    "offset",
                    "q",
                    "sort",
                    "email",
                    "email_q",
                    "formal_name_q",
                    "group_guid",
                    "guid",
                    "is_available_for_contact",
                    "is_company_api_token",
                    "roles_slug",
                    "status",
                ],
                "post_data": {},
                "use_requests_json_for_post": False,
                "method": ["GET"],
                "pagination": True,
                "convert_unders_to_periods": ["roles_slug", "group_guid"],
            },
            "create_user": {
                "endpoint": "ratings/v2/users",
                "params": [],
                "post_data": [
                    "status",
                    "group",
                    "roles",
                    "friendly_name",
                    "is_company_api_token",
                    "is_available_for_contact",
                    "formal_name",
                    "email",
                    "features",
                    "value",
                ],
                "use_requests_json_for_post": True,
                "method": ["POST"],
                "pagination": False,
            },
            "get_user_details": {
                "endpoint": "ratings/v2/users/{guid}",
                "params": ["guid"],
                "post_data": {},
                "use_requests_json_for_post": False,
                "method": ["GET"],
                "pagination": False,
            },
            "edit_user": {
                "endpoint": "ratings/v2/users/{guid}",
                "params": ["guid"],
                "post_data": [
                    "group",
                    "roles",
                    "friendly_name",
                    "is_company_api_token",
                    "is_available_for_contact",
                    "formal_name",
                    "email",
                    "features",
                    "value",
                ],
                "use_requests_json_for_post": True,
                "method": ["PATCH"],
                "pagination": False,
            },
            "delete_user": {
                "endpoint": "ratings/v2/users/{guid}",
                "params": ["guid"],
                "post_data": {},
                "use_requests_json_for_post": False,
                "method": ["DELETE"],
                "pagination": False,
            },
            "turn_on_2fa": {
                "endpoint": "ratings/v2/users/{guid}/require-mfa",
                "params": ["guid"],
                "post_data": {},
                "use_requests_json_for_post": False,
                "method": ["POST"],
                "pagination": False,
            },
            "resend_activation": {
                "endpoint": "ratings/v2/users/{guid}/resend-activation-email",
                "params": ["guid"],
                "post_data": {},
                "use_requests_json_for_post": False,
                "method": ["POST"],
                "pagination": False,
            },
            "reset_2fa": {
                "endpoint": "ratings/v2/users/{guid}/reset-mfa",
                "params": ["guid"],
                "post_data": {},
                "use_requests_json_for_post": False,
                "method": ["POST"],
                "pagination": False,
            },
        },
        "insights": {
            "get_insights": {
                "endpoint": "ratings/v1/insights",
                "params": ["company", "start", "end", "score_delta_lt"],
                "post_data": {},
                "use_requests_json_for_post": False,
                "method": ["GET"],
                "pagination": False,
            },
            "get_change_explanations": {
                "endpoint": "ratings/v1/insights/rating-changes",
                "params": [
                    "limit",
                    "offset",
                    "company",
                    "date_gte",
                    "date_lt",
                    "score_delta_gte",
                    "score_delta_lt",
                ],
                "post_data": {},
                "use_requests_json_for_post": False,
                "method": ["GET"],
                "pagination": True,
            },
        },
        "portfolio": {
            "get_details": {
                "endpoint": "ratings/v2/portfolio",
                "params": [
                    "fields",
                    "format",
                    "limit",
                    "offset",
                    "q",
                    "sort",
                    "countries",
                    "exclude_subscription_type_slug",
                    "filter_group",
                    "risk_vectors_grade",
                    "risk_vectors_slug",
                    "software_category",
                    "software_name",
                    "folder",
                    "industry_name",
                    "industry_slug",
                    "infections",
                    "life_cycle_slug",
                    "open_ports",
                    "products",
                    "product_types",
                    "providers",
                    "rating",
                    "rating_gt",
                    "rating_gte",
                    "rating_lt",
                    "rating_lte",
                    "relationship_slug",
                    "security_incident_categories",
                    "subscriptions_type_slug",
                    "tier",
                    "type",
                    "vendor_action_plan",
                    "vulnerabilities",
                ],
                "post_data": {},
                "use_requests_json_for_post": False,
                "method": ["GET"],
                "pagination": True,
                "convert_unders_to_periods": [
                    "exclude_subscription_type_slug",
                    "risk_vectors_grade",
                    "risk_vectors_slug",
                    "software_category",
                    "software_name",
                    "industry_name",
                    "industry_slug",
                    "life_cycle_slug",
                    "relationship_slug",
                    "subscriptions_type_slug",
                ],
            },
            "get_summary": {
                "endpoint": "ratings/v2/portfolio/summaries",
                "params": ["folder", "tier"],
                "post_data": {},
                "use_requests_json_for_post": False,
                "method": ["GET"],
                "pagination": False,
            },
            "get_public_disclosures": {
                "endpoint": "ratings/v1/portfolio/breaches",
                "params": [
                    "company",
                    "start",
                    "end",
                    "folder",
                    "severity",
                    "severity_gte",
                    "severity_gt",
                    "severity_lte",
                    "severity_lt",
                    "tier",
                ],
                "post_data": {},
                "use_requests_json_for_post": False,
                "method": ["GET"],
                "pagination": False,
            },
            "get_contacts": {
                "endpoint": "ratings/v1/portfolio/contacts",
                "params": [],
                "post_data": {},
                "use_requests_json_for_post": False,
                "method": ["GET"],
                "pagination": False,
            },
            "assign_contact": {
                "endpoint": "ratings/v1/portfolio/contacts",
                "params": [],
                "post_data": [
                    "company_guid",
                    "friendly_name",
                    "formal_name",
                    "email",
                    "phone_number",
                ],
                "use_requests_json_for_post": True,
                "method": ["POST"],
                "pagination": False,
            },
            "edit_contact": {
                "endpoint": "ratings/v1/portfolio/contacts/{guid}",
                "params": ["guid"],
                "post_data": ["guid", "company_guid", "friendly_name", "formal_name", "email", "phone_number"],
                "use_requests_json_for_post": True,
                "method": ["PATCH"],
                "pagination": False,
            },
            "get_geographic_ipspace": {
                "endpoint": "ratings/v1/portfolio/countries",
                "params": [],
                "post_data": {},
                "use_requests_json_for_post": False,
                "method": ["GET"],
                "pagination": False,
            },
            "get_custom_identifiers": {
                "endpoint": "ratings/v1/portfolio/entity-custom-ids",
                "params": [],
                "post_data": {},
                "use_requests_json_for_post": False,
                "method": ["GET"],
                "pagination": False,
            },
            "customize_company_id": {
                "endpoint": "ratings/v1/portfolio/entity-custom-ids",
                "params": [],
                "post_data": ["guid", "name", "custom_id"],
                "use_requests_json_for_post": True,
                "method": ["POST"],
                "pagination": False,
            },
            "bulk_manage_ids": {
                "endpoint": "ratings/v1/portfolio/entity-custom-ids/bulk",
                "params": [],
                "post_data": ["add", "delete"],
                "use_requests_json_for_post": True,
                "method": ["POST"],
                "pagination": False,
            },
        },
    }
)
